In [2]:
import numpy as np

In [3]:
#Seeting up the seed
np.random.seed(42)
#Generating an array of integers
vector = np.random.randint(10, size = 6)
matrix = np.random.randint(10, size = (3, 4))
tensor = np.random.randint(10, size = (3, 4, 5))

tensor

array([[[5, 1, 4, 0, 9],
        [5, 8, 0, 9, 2],
        [6, 3, 8, 2, 4],
        [2, 6, 4, 8, 6]],

       [[1, 3, 8, 1, 9],
        [8, 9, 4, 1, 3],
        [6, 7, 2, 0, 3],
        [1, 7, 3, 1, 5]],

       [[5, 9, 3, 5, 1],
        [9, 1, 9, 3, 7],
        [6, 8, 7, 4, 1],
        [4, 7, 9, 8, 8]]])

In [4]:
#Functions to find out more about dimensionality
print(f'vector - {vector.ndim}')
print(f'matrix - {matrix.ndim}')
print(f'tensor - {tensor.ndim}')


vector - 1
matrix - 2
tensor - 3


In [5]:
#Functions to find out the shape of the array 
print(f'vector - {vector.shape}')
print(f'matrix - {matrix.shape}')
print(f'tensor - {tensor.shape}')

vector - (6,)
matrix - (3, 4)
tensor - (3, 4, 5)


In [6]:
#Functions to find out the number of elements in the array
print(f'vector - {vector.size}')
print(f'matrix - {matrix.size}')
print(f'tensor - {tensor.size}')

vector - 6
matrix - 12
tensor - 60


In [7]:
#Functions to find out the data type of the array
print(f'vector - {vector.dtype}')
print(f'matrix - {matrix.dtype}')
print(f'tensor - {tensor.dtype}')

vector - int32
matrix - int32
tensor - int32


In [8]:
#Getting the first element of different sizes of arrays
print(f'one dimensional - array[0] = {vector[0]}')
print(f'two dimensional - matrix[0][0] = {matrix[0][0]}')
print(f'three dimensional - tensor[0][0][0] = {tensor[0][0][0]}')

one dimensional - array[0] = 6
two dimensional - matrix[0][0] = 2
three dimensional - tensor[0][0][0] = 5


# Slicing vectors and matrices

In [9]:
#Getting the first 3 elements of the array
vector[:3]

array([6, 3, 7])

In [10]:
#Getting the last 3 elements of the array
vector[3:]

array([4, 6, 9])

In [11]:
#Gettin all every 2 element of the array
vector[::2]

array([6, 7, 6])

In [12]:
#Getting only the even column
matrix[:, ::2]

array([[2, 7],
       [3, 7],
       [5, 1]])

In [13]:
#Getting only the first half of columns
matrix[:, :3]

array([[2, 6, 7],
       [3, 7, 7],
       [5, 4, 1]])

In [14]:
#Changing values in array
vector[1] = 99
vector

array([ 6, 99,  7,  4,  6,  9])

In [15]:
#Changing more values using slicing
matrix[:, 0] = np.zeros(3)
matrix

array([[0, 6, 7, 4],
       [0, 7, 7, 2],
       [0, 4, 1, 7]])

In [18]:
#Creating a zero filled vector
np.zeros(3)

array([0., 0., 0.])

In [19]:
#If we pass tupel of values the function will create an array with more dimensions
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
#By the same logic works np.ones function
np.ones(3)

array([1., 1., 1.])

In [21]:
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Creation of copies of arrays in python

In [22]:
fake_copy = vector

#Verifying ids to check if they have the same memory adress
print(id(fake_copy))
print(id(vector))

1451390920144
1451390920144


In [23]:
#For creating a real copy we need to use the copy function
real_copy = vector.copy()

#Checking for the adresses
print(id(real_copy))
print(id(vector))

1451391069424
1451390920144


In [24]:
#Let's see the differences
print(vector)
print(fake_copy)
print(real_copy)

[ 6 99  7  4  6  9]
[ 6 99  7  4  6  9]
[ 6 99  7  4  6  9]


In [25]:
#Changing the vector
vector[0] = 99

#printing the output
print(vector)
print(fake_copy)
print(real_copy)

[99 99  7  4  6  9]
[99 99  7  4  6  9]
[ 6 99  7  4  6  9]


In [26]:
#Concatinating arrays
x1 = np.array([1, 2, 3])
x2 = np.array([4, 5, 6])
np.concatenate([x1, x2])

array([1, 2, 3, 4, 5, 6])

In [27]:
#Concatinating on different axis
matrix = np.array([[1, 2, 3],
                  [4, 5, 6]])
np.concatenate([matrix, matrix])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [28]:
#To concatenate two matrices on columns we should set the parameter axis=1
np.concatenate([matrix, matrix], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [29]:
'''
axis is saying to the function on which axis to concatenate, 
on which dimension on the array to appy it
axis = 1 means the columns
axis = 0 means the rows
'''

'\naxis is saying to the function on which axis to concatenate, \non which dimension on the array to appy it\naxis = 1 means the columns\naxis = 0 means the rows\n'

In [31]:
#You can also use vstack and hstack
#Vstack is used to stack vertically arrays
x = np.array([1, 2, 3])
grid = np.array([[4, 5, 6],
                [7, 8, 9]])
np.vstack([x, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
#Hsrack is used to stack horizontally arrays
x = np.array([[99],
             [99]])
np.hstack([x, grid])

array([[99,  4,  5,  6],
       [99,  7,  8,  9]])